// <auto-generated />
namespace Entry.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EmploeeSalary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmploeeSalary));
        
        string IMigrationMetadata.Id
        {
            get { return "202206061441417_EmploeeSalary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
