// <auto-generated />
namespace Entry.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Project1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Project1));
        
        string IMigrationMetadata.Id
        {
            get { return "202205290703274_Project1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
